# Generated by Django 4.2.1 on 2023-05-17 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_concert_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_concerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
