# Generated by Django 4.2.1 on 2023-05-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='description',
        ),
    ]
